apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: nginx-container
        image: "docker.io/ajayro45/demo:1.0.26" # {"$imagepolicy": "flux-system:demo-image-policy"} 
        ports:
        - containerPort: 80
