apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: nginx-container
        image: "docker.io/ajayro45/demo:7c8be197ffa8abe84642e4f525a282956dce5e3c" # {"$imagepolicy": "flux-system:demo-image-policy"} 
        ports:
        - containerPort: 80
