name: Demo Application CI
on:
  workflow_dispatch: 
  push:
    branches:
      - 'feature/*'
      
jobs:
  Checkout-Repo:
    name: Checkout repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
  Docker-Build-Push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: Checkout-Repo
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for commit count
          
      - name: Generate semantic version
        id: version
        run: |
          # Get commit count for patch version
          COMMIT_COUNT=$(git rev-list --count HEAD)
          
          # Set major and minor versions manually, patch auto-increments
          MAJOR=1
          MINOR=0
          PATCH=$COMMIT_COUNT
          
          VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "🏷️ Building version: ${VERSION}"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Docker Build and push with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/demo:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Output build info
        run: |
          echo "📦 ${{ vars.DOCKERHUB_USERNAME }}/demo:${{ steps.version.outputs.version }}"
